### ISSUE TITLE
Board Not Found

### ISSUE THREAD

**Issue by nishantmodak** [austinbv/dino#41]
After having followed the steps.. I just keep getting 

```
/dino/lib/dino/tx_rx/usb_serial.rb:17:in `io': Dino::BoardNotFound (Dino::BoardNotFound)
    from /home/nm/projects/dino/lib/dino/tx_rx/usb_serial.rb:44:in `write'
    from /home/nm/projects/dino/lib/dino/board.rb:47:in `write'
    from /home/nm/projects/dino/lib/dino/board.rb:111:in `send_clearing_bytes'
    from /home/nm/projects/dino/lib/dino/board.rb:9:in `initialize'
    from examples/led/led.rb:8:in `new'
    from examples/led/led.rb:8:in `<main>'
```

**Comment by ensaaj** [comment]
I am using Dino 0.11.2 and test an Arduino Uno on Ubuntu 12.04.  Just started learning this very interesting Ruby language and tried the jumpstartlab excellent tutoriol.  When  the baudrate from the default value given by the tutoriol (115200).. everything work fine eventhough the same warnings are given,, but the terminal and arduno board indicate both are communication.  But when change to 9600 baudrate the same warnings appear but ardunio and Ruby does not work.. Hope this helps

regards 
Aziz

**Comment by vickash** [comment]
Have you changed the baud rate in the sketch and re-flashed the board? Both the board and the ruby script need to use the same baud rate.

**Comment by ensaaj** [comment]
Dear Mr Vickash

Yup.. I change the baudrate in du.ino ( using Arduino IDE 1.0.1) from 115200 to 9600(not working) and flash the modified sketch to the arduino board.  I cannot find baudrate setting for myfile.rb.

**Comment by vickash** [comment]
Initializing the board (and TxRx) should look something like this if you have to set baud to 9600:
````ruby
board = Dino::Board.new(Dino::TxRx::Serial.new(baud: 9600)
````
Try that and see if it works.

**Comment by ensaaj** [comment]
Dear Mr Viskash

Do i have to add require 'serialport' ?.. and additional close bracket.  When I change the baudrate to the serial port, du.ino sketch and blink.rb , the board and ruby is no loger talking and i have the following messages

/home/toshiba/.rvm/gems/ruby-2.1.1/gems/dino-0.11.2/lib/dino/tx_rx/base.rb:43: warning: ambiguous first argument; put parentheses or even spaces
/home/toshiba/.rvm/gems/ruby-2.1.1/gems/dino-0.11.2/lib/dino/tx_rx/serial.rb:40: warning: ambiguous first argument; put parentheses or even spaces
/home/toshiba/.rvm/gems/ruby-2.1.1/gems/dino-0.11.2/lib/dino/board.rb:99: warning: ambiguous first argument; put parentheses or even spaces
/home/toshiba/.rvm/gems/ruby-2.1.1/gems/dino-0.11.2/lib/dino/tx_rx/base.rb:52:in `handshake': Dino::BoardNotFound (Dino::BoardNotFound)
	from /home/toshiba/.rvm/gems/ruby-2.1.1/gems/dino-0.11.2/lib/dino/tx_rx/serial.rb:23:in `handshake'
	from /home/toshiba/.rvm/gems/ruby-2.1.1/gems/dino-0.11.2/lib/dino/board.rb:13:in `handshake'
	from /home/toshiba/.rvm/gems/ruby-2.1.1/gems/dino-0.11.2/lib/dino/board.rb:9:in `initialize'
	from dino.rb:9:in `new'
	from dino.rb:9:in `<main>'

**Comment by ensaaj** [comment]
Dear Mr Vickash

The program works at baudrate 38400..

**Comment by vickash** [comment]
Sorry. There was a mistake in my code above. Forgot a ")" at the end.

It should be:
````ruby
board = Dino::Board.new(Dino::TxRx::Serial.new(baud: 9600))
````
If you got it to work at higher rates, I guess you figured that out eventually.

Another thing you can try is using the 0.12-wip branch. You will need to know a little about git and Ruby's `gem` command to get it going. Because it isn't released yet, you can't use `gem install`, but google for "build gem from source" and you should be able to figure it out.

It uses a much better serial library. That may work at 9600. I've never tested at 9600 to be honest.
