### ISSUE TITLE
Board Not Found

### ISSUE THREAD

**Issue by kd-kraken** [austinbv/dino#55]
Had problems connecting to the board from Ubuntu linux:

/var/lib/gems/1.9.1/gems/dino-0.11.2/lib/dino/tx_rx/base.rb:52:in `handshake': Dino::BoardNotFound (Dino::BoardNotFound)
        from /var/lib/gems/1.9.1/gems/dino-0.11.2/lib/dino/tx_rx/serial.rb:23:in`handshake'
        from /var/lib/gems/1.9.1/gems/dino-0.11.2/lib/dino/board.rb:13:in `handshake'
        from /var/lib/gems/1.9.1/gems/dino-0.11.2/lib/dino/board.rb:9:in`initialize'

My fix was to add:
def on_linx?; RUBY_PLATFORM.match /linux/; end

and change handshake to:
if on_windows? or on_linux?

Working for me now.

**Comment by hanjeongjin** [comment]
do anyone knew some step-by-step video on how to setup dino to uploading the du.ino bootstrap?
I really can't get the basic blinking led.rb
i can't make it work. pls help
