### ISSUE TITLE
Handshake Issue on Windows Machines

### ISSUE THREAD

**Issue by wengzilla** [austinbv/dino#66]
Running into a handshake issue on Windows machines for the 0.11.2 gem version. 

`board = Dino::Board.new(Dino::TxRx::Serial.new)` seems to be timing out. Gem version 0.10.0 still works well...

See backtrace here: https://gist.github.com/wengzilla/7d473529139c6d904b87

**Comment by vickash** [comment]
As of https://github.com/austinbv/dino/commit/7fcf387132dbda80f7ae34d203e71cb113da7e9e, we are using the `rubyserial` gem, I have made the handshake routine better, and there are a couple other fixes  for enumerating the callbacks hash that raised exceptions in Windows.

I have tested that commit extensively on Windows XP and 7 for both input and output and it's more reliable than anything previously done with the `serialport` gem. However, you must still **explicitly specify the COM port**. Enumeration doesn't work like in *nix yet.
