### ISSUE TITLE
Program stops on board att

### ISSUE THREAD

**Issue by jotapem** [austinbv/dino#81]
I installed Dino yesterday and I'm having problems trying to execute the simple blinking program.
I realized that the program 'gets stuck' on the `board = Dino::Board.new(Dino::TxRx::Serial.new)`line. 
(I also tried  `board = Dino::Board.new(Dino::TxRx.new)`)

I kept regenerating and reuploading the sketches and a few minutes ago I got the Board Not Found error. Then I reinstalled Dino and I'm back to the same situation: the program is running forever and is not logging a thing.

**Comment by vickash** [comment]
Which arduino board and what OS?

**Comment by jotapem** [comment]
arduino UNO and windows 7

**Comment by vickash** [comment]
Which branch? master simply won't work at all on Windows because of a problem with the `serialport` gem. You'd need to try 0.12, which I switched to use the `rubyserial` gem a few days ago. Have not tested on Windows yet, but it should work.

**Comment by jotapem** [comment]
I replaced the files with the 0.12 branch files, but now I'm getting these errors on the `require 'dino'` line

![dino_err](https://cloud.githubusercontent.com/assets/10497742/5739156/b8002280-9bdc-11e4-9711-689371324c96.png)

**Comment by vickash** [comment]
Run `bundle install`

**Comment by jotapem** [comment]
the bundle is now complete and the `require 'dino'` line does not log any errors, but the `board = Dino::Board.new(Dino::TxRx.new)` now log these:

![dino_err](https://cloud.githubusercontent.com/assets/10497742/5739304/57b71304-9bdf-11e4-8990-220bb11e186e.png)

**Comment by vickash** [comment]
Ruby's still finding the old version (master branch), you installed via rubygems. 0.11.2 and 0.12.0 are not compatible. Remove the old one by running `gem uninstall dino`. Remove everything.

You can install 0.12 into your system by building it and then installing. In the source directory for 0.12 run:
`gem build dino.gemspec`
`gem install dino-0.12.0.gem`

**Comment by jotapem** [comment]
I succesfully ran the 3 lines you told me to, but I'm getting errors on `dino` and `dino generate-sketch serial`

![dino_err](https://cloud.githubusercontent.com/assets/10497742/5855453/8a756728-a21f-11e4-8efd-b944fbf6fc63.png)

I figured I should have deleted even more stuff, so I just reinstalled Ruby then built dino-0.12 and I'm getting the exact same error log

**Comment by vickash** [comment]
Check if file `C:/Ruby193/lib/ruby/gems/1.9.1/gems/dino-0.12.0/lib/dino_cli.rb` exists. It's saying it can't find the file that should be at that path.

I tried building the gem from source in Ruby 1.9.3 under windows XP and couldn't recreate your error.
